"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-19 13:06:07.891835
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=60), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ip_hash', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_audit_ts', ['ts'], unique=False)

    op.create_table('models',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('public_id', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('upstream_model', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('output_price_per_1m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_models_public_id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_public_id'), ['public_id'], unique=False)

    op.create_table('provider_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('provider_type', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.String(length=400), nullable=False),
    sa.Column('auth_mode', sa.String(length=20), nullable=False),
    sa.Column('key_masked', sa.String(length=60), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('model_mapping', sa.JSON(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_configs_name'), ['name'], unique=True)

    op.create_table('rate_limit_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=60), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('rph', sa.Integer(), nullable=True),
    sa.Column('rpd', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpd', sa.Integer(), nullable=True),
    sa.Column('concurrency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_id', name='uq_rate_limit_scope')
    )
    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_configs_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_configs_scope_type'), ['scope_type'], unique=False)

    op.create_table('rate_limit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('api_key_id', sa.String(length=40), nullable=True),
    sa.Column('limit_type', sa.String(length=30), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_events_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_events_user_id'), ['user_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('api_key_id', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('upstream_model', sa.String(length=120), nullable=True),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('api_format', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('ttft_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('token_count_source', sa.String(length=30), nullable=False),
    sa.Column('provider_request_id', sa.String(length=120), nullable=True),
    sa.Column('error_type', sa.String(length=60), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_content', sa.Text(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requests_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_model'), ['model'], unique=False)
        batch_op.create_index('ix_requests_model_started', ['model', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_requests_project_started', ['project_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_status'), ['status'], unique=False)
        batch_op.create_index('ix_requests_status_started', ['status', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_requests_user_started', ['user_id', 'started_at'], unique=False)

    op.create_table('usage_aggregates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_sum_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket', 'user_id', 'project_id', 'model', name='uq_usage_aggregate_bucket')
    )
    with op.batch_alter_table('usage_aggregates', schema=None) as batch_op:
        batch_op.create_index('ix_usage_agg_bucket', ['bucket'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('api_key_id', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_project_ts', ['project_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_user_ts', ['user_id', 'ts'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('quota_tokens', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('concurrency_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=True),
    sa.Column('allowed_models', sa.JSON(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('upstream_conversation_id', sa.String(length=200), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))

    op.drop_table('conversations')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_status'))
        batch_op.drop_index(batch_op.f('ix_api_keys_project_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))

    op.drop_table('api_keys')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_ts')
        batch_op.drop_index(batch_op.f('ix_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_ts'))
        batch_op.drop_index(batch_op.f('ix_usage_records_request_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_api_key_id'))
        batch_op.drop_index('ix_usage_project_ts')

    op.drop_table('usage_records')
    with op.batch_alter_table('usage_aggregates', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_agg_bucket')

    op.drop_table('usage_aggregates')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index('ix_requests_user_started')
        batch_op.drop_index(batch_op.f('ix_requests_user_id'))
        batch_op.drop_index('ix_requests_status_started')
        batch_op.drop_index(batch_op.f('ix_requests_status'))
        batch_op.drop_index(batch_op.f('ix_requests_started_at'))
        batch_op.drop_index('ix_requests_project_started')
        batch_op.drop_index(batch_op.f('ix_requests_project_id'))
        batch_op.drop_index('ix_requests_model_started')
        batch_op.drop_index(batch_op.f('ix_requests_model'))
        batch_op.drop_index(batch_op.f('ix_requests_api_key_id'))

    op.drop_table('requests')
    with op.batch_alter_table('rate_limit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_events_ts'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_events_api_key_id'))

    op.drop_table('rate_limit_events')
    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_configs_scope_type'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_configs_scope_id'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_configs_created_at'))

    op.drop_table('rate_limit_configs')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_name'))
        batch_op.drop_index(batch_op.f('ix_provider_configs_created_at'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_public_id'))
        batch_op.drop_index(batch_op.f('ix_models_enabled'))
        batch_op.drop_index(batch_op.f('ix_models_created_at'))

    op.drop_table('models')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_ts')
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
