"""enterprise admin module

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-19 15:31:14.928202
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=60), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_credit_org_ts', ['organization_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('subscription_id', sa.String(length=40), nullable=True),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_fee_usd', sa.Float(), nullable=False),
    sa.Column('usage_usd', sa.Float(), nullable=False),
    sa.Column('credits_applied_usd', sa.Float(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_org_period', ['organization_id', 'period_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('limit_overrides',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=60), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('limit_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_limit_overrides_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_limit_overrides_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_limit_overrides_scope_type'), ['scope_type'], unique=False)

    op.create_table('model_prices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model_public_id', sa.String(length=120), nullable=False),
    sa.Column('input_price_per_1m', sa.Float(), nullable=False),
    sa.Column('output_price_per_1m', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_prices', schema=None) as batch_op:
        batch_op.create_index('ix_model_price_lookup', ['model_public_id', 'effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_prices_model_public_id'), ['model_public_id'], unique=False)

    op.create_table('plan_history',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('old_plan', sa.String(length=60), nullable=True),
    sa.Column('new_plan', sa.String(length=60), nullable=False),
    sa.Column('changed_by', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_history_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_history_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_history_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('price_monthly_usd', sa.Float(), nullable=False),
    sa.Column('price_yearly_usd', sa.Float(), nullable=False),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_slug'), ['slug'], unique=True)

    op.create_table('quota_reset_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('previous_usage', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reset_by', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quota_reset_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quota_reset_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quota_reset_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_quota_reset_events_user_id'), ['user_id'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index('ix_risk_event_ts', ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('ip_hash', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=40), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('ix_security_event_ts', ['ts'], unique=False)
        batch_op.create_index('ix_security_event_user_ts', ['user_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_status'), ['status'], unique=False)

    op.create_table('plan_features',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_feature')
    )
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_features_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_limits',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'metric', name='uq_plan_limit')
    )
    with op.batch_alter_table('plan_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_limits_plan_id'), ['plan_id'], unique=False)

    op.create_table('plan_models',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('model_public_id', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'model_public_id', name='uq_plan_model')
    )
    with op.batch_alter_table('plan_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_models_plan_id'), ['plan_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('plan_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('trial_status', sa.String(length=20), nullable=False),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_api_keys_organization_id', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=40), nullable=True))
        # server_default backfills existing rows; the ORM supplies the value on new rows.
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_projects_organization_id', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usage_aggregates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granularity', sa.String(length=10), nullable=False, server_default='hour'))
        batch_op.add_column(sa.Column('organization_id', sa.String(length=40), nullable=False, server_default=''))
        batch_op.drop_constraint(batch_op.f('uq_usage_aggregate_bucket'), type_='unique')
        batch_op.create_unique_constraint('uq_usage_aggregate_bucket', ['granularity', 'bucket', 'organization_id', 'user_id', 'project_id', 'model'])
        batch_op.create_index('ix_usage_agg_gran_bucket', ['granularity', 'bucket'], unique=False)

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('credits_used', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='success'))
        batch_op.add_column(sa.Column('input_price_snapshot', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('output_price_snapshot', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_usage_records_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=False, server_default='free'))
        batch_op.add_column(sa.Column('admin_role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('admin_permissions', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('primary_org_id', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_primary_org_id'), ['primary_org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_primary_org_id'))
        batch_op.drop_column('primary_org_id')
        batch_op.drop_column('admin_permissions')
        batch_op.drop_column('admin_role')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_organization_id'))
        batch_op.drop_column('output_price_snapshot')
        batch_op.drop_column('input_price_snapshot')
        batch_op.drop_column('status')
        batch_op.drop_column('credits_used')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('usage_aggregates', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_agg_gran_bucket')
        batch_op.drop_constraint('uq_usage_aggregate_bucket', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_usage_aggregate_bucket'), ['bucket', 'user_id', 'project_id', 'model'])
        batch_op.drop_column('organization_id')
        batch_op.drop_column('granularity')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_constraint('fk_api_keys_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_created_at'))

    op.drop_table('organization_members')
    with op.batch_alter_table('plan_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_models_plan_id'))

    op.drop_table('plan_models')
    with op.batch_alter_table('plan_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_limits_plan_id'))

    op.drop_table('plan_limits')
    with op.batch_alter_table('plan_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_features_plan_id'))

    op.drop_table('plan_features')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_created_at'))

    op.drop_table('organizations')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_ts'))
        batch_op.drop_index(batch_op.f('ix_security_events_organization_id'))
        batch_op.drop_index('ix_security_event_user_ts')
        batch_op.drop_index('ix_security_event_ts')

    op.drop_table('security_events')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_type'))
        batch_op.drop_index(batch_op.f('ix_risk_events_ts'))
        batch_op.drop_index(batch_op.f('ix_risk_events_status'))
        batch_op.drop_index(batch_op.f('ix_risk_events_organization_id'))
        batch_op.drop_index('ix_risk_event_ts')

    op.drop_table('risk_events')
    with op.batch_alter_table('quota_reset_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quota_reset_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_quota_reset_events_ts'))
        batch_op.drop_index(batch_op.f('ix_quota_reset_events_organization_id'))

    op.drop_table('quota_reset_events')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_slug'))
        batch_op.drop_index(batch_op.f('ix_plans_created_at'))

    op.drop_table('plans')
    with op.batch_alter_table('plan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_plan_history_ts'))
        batch_op.drop_index(batch_op.f('ix_plan_history_organization_id'))

    op.drop_table('plan_history')
    with op.batch_alter_table('model_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_prices_model_public_id'))
        batch_op.drop_index('ix_model_price_lookup')

    op.drop_table('model_prices')
    with op.batch_alter_table('limit_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_limit_overrides_scope_type'))
        batch_op.drop_index(batch_op.f('ix_limit_overrides_scope_id'))
        batch_op.drop_index(batch_op.f('ix_limit_overrides_expires_at'))

    op.drop_table('limit_overrides')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))
        batch_op.drop_index('ix_invoice_org_period')

    op.drop_table('invoices')
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_ts'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transactions_organization_id'))
        batch_op.drop_index('ix_credit_org_ts')

    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
